### PR TITLE
Dismiss progress message when child_process is exited

### PR DESCRIPTION
**Pull request by MangelMaxime**
Without the change in this PR, the Progress info is displayed until the user dismiss the notification from:

- https://github.com/ionide/ionide-vscode-mechanic/compare/feature/better_progress?expand=1#diff-7cdab5b04495ab8b5707e111f2a676d1R57
- https://github.com/ionide/ionide-vscode-mechanic/compare/feature/better_progress?expand=1#diff-7cdab5b04495ab8b5707e111f2a676d1R62

### CODE REVIEW

**Comment by forki** [comment]
btw: 0.0.7 still opens a terminal for me

**Comment by MangelMaxime** [comment]
@forki You speak about the terminal, that need to be closed by pressing enter in VSCode ? Or a new window terminal ?

If it's the first, I think this is the Windows way to do it...

**Comment by forki** [comment]
that thing from the screenshot. a shot flickering windows terminal.

**Comment by MangelMaxime** [comment]
Oh ? But I removed the `shell ==> true` property...

**Comment by forki** [comment]
ok. needed to restart code. never mind

**Pull request merged**
