### PR TITLE
Port Ionide's release process over

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@forki We need to change this [line](https://github.com/ionide/ionide-vscode-mechanic/blob/003c1021b254167a517010d793b4715218bc93d5/release/package.json#L3) too.

I think we should write `"publisher": "Ionide",`

**Comment by MangelMaxime** [comment]
Other than that seems good for me.

**Comment by MangelMaxime** [comment]
This PR broke the plugin, I have the fix in my local version will publish it shortly

**Comment by forki** [comment]
already fixed on master

**Comment by MangelMaxime** [comment]
https://twitter.com/MangelMaxime/status/973550199133130752

<3

**Pull request merged**
